# Generated by Django 4.2.7 on 2023-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carrental_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='user',
        ),
    ]
